### ISSUE TITLE
assertion error in Trainer when training data points were discarded

### ISSUE THREAD

**Issue by janfb** [mackelab/delfi#11]
In `Trainer` line 61 there is an assertion to make sure that `trn_data` length is consistent between parameter, summary stats and the importance weights `iws`.  If during the generation of training data some samples were discarded then there is a mismatch because `iws` is pre-located with the original number of training samples (in `SNPE.py`). In that case the assertion error is raised.

**Comment by janfb** [comment]
A potential fix would be to pre-locate the `iws` in `SNPE.py` with the updated `n_train_round`, e.g., `n_train_round = trn_data[0].shape[0]`.

**Comment by jan-matthis** [comment]
Fixed, thanks for spotting this!
