### ISSUE TITLE
Loop reference

### ISSUE THREAD

**Issue by florensacc** [mackelab/delfi#52]
The latest version of you repo has a loop reference that prevents it from working correctly:
when trying to `import delfi.distribution as dd`, this new line tries to import a module that in turn tries to import distribution: https://github.com/mackelab/delfi/blob/master/delfi/distribution/__init__.py#L9

**Comment by dgreenberg** [comment]
Thanks for pointing this out. To be honest I'm not sure how this got past the tests but it will be fixed shortly.
