### ISSUE TITLE
Is the low sampling acceptance rate normal when doing sampling using CMAF density and atomic proposal?

### ISSUE THREAD

**Issue by holmosaint** [mackelab/delfi#66]
Hi, thanks in advance for your attention. I just got a new problem when I simulated the HH model with 7 parameters. During the 2nd round drawing parameters, it was quite slow due to the fact that the majority of the parameters sampled was out of range. Is this case normal or do you have any suggestions to solve the problem?

Also, the problem occurs in other models as well. Looking forward to your suggestions.

**Comment by jan-matthis** [comment]
The problem of low acceptance rate with APT/SNPE-C when posteriors have bounded supported is an open issue, see [Greenberg et al. (2019)](https://arxiv.org/abs/1905.07488) and [Durkan et al. (2020)](https://arxiv.org/abs/2002.03712) for some discussion. In the future, we will have options to alleviate it, e.g., MCMC sampling, but unfortunately no quick fix right now.

**Comment by holmosaint** [comment]
Thanks for the information and looking forward to seeing your progress on that.
