### ISSUE TITLE
Broken pipe error while running the tutorial 

### ISSUE THREAD

**Issue by moukati** [mackelab/delfi#68]
I am using the windows version and while running the Hodgkin Huxley example from the tutorial with spyder(same exact code of the tutorial) I receive this error:
____________________________________________
Traceback (most recent call last):

  File "E:\courses\mini-project\HH.py", line 441, in <module>
    density=density)

  File "c:\users\mosi\delfi\delfi\inference\APT.py", line 65, in __init__
    verbose=verbose, **kwargs)  # initializes network

  File "c:\users\mosi\delfi\delfi\inference\BaseInference.py", line 61, in __init__
    params, stats = generator.gen(1, skip_feedback=True, verbose=False)

  File "c:\users\mosi\delfi\delfi\generator\MPGenerator.py", line 197, in gen
    return self.run_model(params, skip_feedback=skip_feedback, verbose=verbose, **kwargs)

  File "c:\users\mosi\delfi\delfi\generator\MPGenerator.py", line 210, in run_model
    self.start_workers()

  File "c:\users\mosi\delfi\delfi\generator\MPGenerator.py", line 134, in start_workers
    w.start()

  File "C:\Users\mosi\anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)

  File "C:\Users\mosi\anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "C:\Users\mosi\anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "C:\Users\mosi\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\Users\mosi\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

BrokenPipeError: [Errno 32] Broken pipe  
_______________________________________________
I don't know exactly what the problem is but I guess it may be related to my cpu or multiprocessing implementation of python on windows. 

I tried to limit the number of threads to one with the following code but that didn't solve the problem either.
__________________
import os
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
_____________________
Another thing I did was reducing the number of generators processor to 1(number of my processor cores is 2) which didn't work either, but one thing was added to the error explenation:
___________________
Exception ignored in: <function MPGenerator.__del__ at 0x000001B6432E4828>
Traceback (most recent call last):
  File "c:\users\mosi\delfi\delfi\generator\MPGenerator.py", line 299, in __del__
    self.stop_workers()
  File "c:\users\mosi\delfi\delfi\generator\MPGenerator.py", line 139, in stop_workers
    if self.workers is None:
AttributeError: 'MPGenerator' object has no attribute 'workers'
_____________________
I would be grateful if anyone could share ideas about this issue

**Comment by jan-matthis** [comment]
> I don't know exactly what the problem is but I guess it may be related to my cpu or multiprocessing implementation of python on windows.

Yes, from the error message `AttributeError: 'MPGenerator' object has no attribute 'workers'` the multiprocessing generator (`MPGenerator`) is involved. To confirm: Does the tutorial run when you use `g = dg.Default(model=m, prior=prior, summary=s)` instead of `g = dg.MPGenerator(models=m, prior=prior, summary=s`? 

That would offer you a way to at least run the example on a single process (which should be reasonably quick).

To figure out how to resolve the error, it would be important to know the exact versions of packages you are using. If you are using `conda` or `virtual environments` it is possible to generate lists of installed packages using `conda list` or `pip list` respectively. With that information in hand we might be able to reproduce the error and find a solution.

CC: @kaandocal, @dgreenberg

**Comment by kaandocal** [comment]
I have uploaded a fix for the second error you mentioned (`AttributeError: 'MPGenerator' object has no attribute 'workers'`), please let me know if it works.

I am less sure about the `BrokenPipeError`; after some quick research it seems to be a problem specific to Windows and `multiprocessing`. If that is the case the standard suggestion is enclosing your code in a statement of the form

```
if __name__ = '__main__':
    # (Your code goes here)
```
Does that solve your problem?

**Comment by moukati** [comment]
> I have uploaded a fix for the second error you mentioned (`AttributeError: 'MPGenerator' object has no attribute 'workers'`), please let me know if it works.
> 
> I am less sure about the `BrokenPipeError`; after some quick research it seems to be a problem specific to Windows and `multiprocessing`. If that is the case the standard suggestion is enclosing your code in a statement of the form
> 
> ```
> if __name__ = '__main__':
>     # (Your code goes here)
> ```
> 
> Does that solve your problem?

The correct syntax is this I think: 
if __name__ == "__main__":

No, it didn't work, still gives the broken pipe error, 

I used it like this:

if __name__ == "__main__": 
       res = infer.SNPEC(g, obs=obs_stats, n_hiddens=n_hiddens, seed=seed_inf, pilot_samples=pilot_samples, n_mades=n_mades, prior_norm=prior_norm, density=density)


is it what you meant by using(if __name__ == "__main__":)?

**Comment by kaandocal** [comment]
The solution I proposed (with underscores as written) should prevent
your code from running a second time in the child processes. Try using
it around your main code, including the line where you create the
generator.

**Comment by moukati** [comment]
> I have uploaded a fix for the second error you mentioned (`AttributeError: 'MPGenerator' object has no attribute 'workers'`), please let me know if it works.
> 
> I am less sure about the `BrokenPipeError`; after some quick research it seems to be a problem specific to Windows and `multiprocessing`. If that is the case the standard suggestion is enclosing your code in a statement of the form
> 
> ```
> if __name__ = '__main__':
>     # (Your code goes here)
> ```
> 
> Does that solve your problem?

I used this part of the code after the line you said: 

res = infer.SNPEC(g, obs=obs_stats, n_hiddens=n_hiddens, seed=seed_inf, pilot_samples=pilot_samples, n_mades=n_mades, prior_norm=prior_norm, density=density)
also including the line where the generator is created. 

It still doesn't work and gives the broken pipe error. 

> > I don't know exactly what the problem is but I guess it may be related to my cpu or multiprocessing implementation of python on windows.
> 
> Yes, from the error message `AttributeError: 'MPGenerator' object has no attribute 'workers'` the multiprocessing generator (`MPGenerator`) is involved. To confirm: Does the tutorial run when you use `g = dg.Default(model=m, prior=prior, summary=s)` instead of `g = dg.MPGenerator(models=m, prior=prior, summary=s`?
> 
> That would offer you a way to at least run the example on a single process (which should be reasonably quick).
> 
> To figure out how to resolve the error, it would be important to know the exact versions of packages you are using. If you are using `conda` or `virtual environments` it is possible to generate lists of installed packages using `conda list` or `pip list` respectively. With that information in hand we might be able to reproduce the error and find a solution.
> 
> CC: @kaandocal, @dgreenberg

Yes it runs with g = dg.Default(model=m, prior=prior, summary=s)

I attached the conda list: 
[conda list.txt](https://github.com/mackelab/delfi/files/4563671/conda.list.txt)

**Comment by jan-matthis** [comment]
@moukati, I am closing this issue since it has been stale for a while and things seems to run with `g = dg.Default(model=m, prior=prior, summary=s)`. We have stopped active development of `delfi` and shifted our efforts to `sbi` which is available here: https://github.com/mackelab/sbi/ (multi-processing is supported as well).
